# Generated by Django 5.2.8 on 2025-11-17 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gutenberg_id', models.IntegerField(unique=True)),
                ('filename', models.CharField(max_length=300, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('authors', models.CharField(blank=True, max_length=500)),
                ('language', models.CharField(max_length=10)),
                ('word_count', models.PositiveIntegerField()),
                ('content', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvertedIndexEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(db_index=True, max_length=100)),
                ('count', models.PositiveIntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='index_entries', to='moteur.book')),
            ],
            options={
                'indexes': [models.Index(fields=['term'], name='moteur_inve_term_023f58_idx'), models.Index(fields=['book'], name='moteur_inve_book_id_7eca0e_idx')],
                'unique_together': {('term', 'book')},
            },
        ),
    ]
